name: build
on:
  push:
  schedule:
    - cron: '30 3 * * *'

jobs:
  install:
    runs-on: ubuntu-latest

    container:
      image: rbernon/winetest-windows:stable
      options: --user root --device=/dev/kvm --device=/dev/net/tun --cap-add NET_ADMIN -p 8006:8006

    env:
      VERSION: 10

    steps:
      - name: Check
        id: cache-check
        uses: actions/cache/restore@v4
        with:
          lookup-only: true
          path: /storage
          key:
            storage-${{ github.run_id }}
          restore-keys: |
            storage

      - name: Cache
        if: steps.cache-check.outputs.cache-hit == ''
        uses: actions/cache@v4
        with:
          path: /storage
          key:
            storage-${{ github.run_id }}
          restore-keys: |
            storage

      - name: Install
        if: steps.cache-check.outputs.cache-hit == ''
        run: |
          mkisofs -J -o /drivers.iso /data
          chmod +x /run/entry.sh
          /usr/bin/tini -s -- /run/entry.sh
          rm -f /drivers.iso

  winetest:
    runs-on: ubuntu-latest
    needs: install

    container:
      image: rbernon/winetest-windows:stable
      options: --user root --device=/dev/kvm --device=/dev/net/tun --cap-add NET_ADMIN -p 8006:8006

    strategy:
      matrix:
        arch: [wow64, win64]
        version: [w10pro64]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Cache
        uses: actions/cache/restore@v4
        with:
          path: /storage
          key:
            storage-${{ github.run_id }}
          restore-keys: |
            storage

      - name: Execute
        timeout-minutes: 90
        run: |
          $PWD/test-windows ${{ matrix.version }} ${{ matrix.arch }} ${{ github.event_name }}

      - name: Upload
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-${{ matrix.version }}-${{ matrix.arch }}.report
          path: /data/winetest.report

  clean:
    needs: winetest
    runs-on: ubuntu-latest
    steps:
      - name: Cleanup
        uses: rbernon/workflow-cleanup@main
        with:
          workflow: all
